### ISSUE TITLE
huggingface将下载好的数据下载到本地，通过本地加载的方式报错。

### ISSUE THREAD

**Issue by amanyara** [esbatmop/MNBVC#44]
![image](https://github.com/esbatmop/MNBVC/assets/73683903/713ed96e-ab2b-44fb-a51d-5fd54735ae59)
Traceback (most recent call last):
  File "F:\Data-King\multi_dialogue.py", line 2, in <module>
    dataset = load_from_disk("MNBVC")
  File "D:\Anaconda3\envs\zyh\lib\site-packages\datasets\load.py", line 1907, in load_from_disk
    f"Directory {dataset_path} is neither a `Dataset` directory nor a `DatasetDict` directory."
FileNotFoundError: Directory MNBVC is neither a `Dataset` directory nor a `DatasetDict` directory.

from datasets import load_dataset, load_from_disk
dataset = load_from_disk("MNBVC")

next(iter(dataset))  # get the first line

**Comment by amanyara** [comment]
已解决
